# Generated by Django 5.2.3 on 2025-06-24 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Shtrix kod')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Dona'), ('liter', 'Litr'), ('meter', 'Metr')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Partiya raqami')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotib olish narxi')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotuv narxi')),
                ('initial_quantity', models.IntegerField(verbose_name="Boshlang'ich miqdor")),
                ('remaining_quantity', models.IntegerField(verbose_name='Qolgan miqdor')),
                ('arrival_date', models.DateField(verbose_name='Kelgan sana')),
                ('expiry_date', models.DateField(verbose_name='Yaroqlilik muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pos_app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot partiyasi',
                'verbose_name_plural': 'Mahsulot partiyalari',
                'ordering': ['arrival_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True, verbose_name='Savdo raqami')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soliq miqdori')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=10, verbose_name="To'lov usuli")),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'langan summa")),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qaytim')),
                ('status', models.CharField(choices=[('completed', 'Yakunlangan'), ('returned', 'Qaytarilgan'), ('partially_returned', 'Qisman qaytarilgan')], default='completed', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='Qaytarish raqami')),
                ('total_return_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qaytarilgan summa')),
                ('reason', models.TextField(blank=True, verbose_name='Qaytarish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qaytarilgan vaqt')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.sale', verbose_name='Asl savdo')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('returned_quantity', models.IntegerField(default=0, verbose_name='Qaytarilgan miqdor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.productbatch', verbose_name='Partiya')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_app.sale', verbose_name='Savdo')),
            ],
            options={
                'verbose_name': 'Savdo elementi',
                'verbose_name_plural': 'Savdo elementlari',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.IntegerField(verbose_name='Qaytarilgan miqdor')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qaytarilgan summa')),
                ('return_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_app.returnsale')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.saleitem')),
            ],
            options={
                'verbose_name': 'Qaytarish elementi',
                'verbose_name_plural': 'Qaytarish elementlari',
            },
        ),
    ]
